algorithms:
  - name: PWDefault
    params: {
      "algo/default/graph_reduction/arcs/active": 1,
      "algo/default/graph_reduction/arcs/cutoff": 0.4,
      "algo/default/graph_reduction/arcs/k1": 0.2,
      "algo/default/graph_reduction/arcs/k2": 0.2,

      "algo/default/graph_reduction/nodes/active": 1,
      "algo/default/graph_reduction/nodes/cutoff": 0.9,
      "algo/default/graph_reduction/nodes/k3": 0.7,
      "algo/default/graph_reduction/nodes/k4": 0.3,
      "algo/default/graph_reduction/nodes/k5": 0.1,

    }

time_limits: [100]
instances:
  - ../instances/spprclib